CREATE GENERATOR GEN_USERS_U_ID;
SET GENERATOR GEN_USERS_U_ID TO 0;
CREATE TRIGGER USERS_BI_TR FOR USERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.U_ID is NULL) then NEW.U_ID = GEN_ID(GEN_USERS_U_ID, 1);
END